### ISSUE TITLE
package name doesn't use "contrib" convention

### ISSUE THREAD

**Issue by knolleary** [mapero/node-red-contrib-mosca#1]
Hi,

just saw this appear in my search for node-red nodes. One small comment - you've named the repository `node-red-contrib-mosca`, using the node-red-contrib- convention - but the name in `package.json` (and thus the name of the npm package) is `node-red-node-mosca`.

We would ask that the npm name also use the `contrib` naming convention to avoid confusion with nodes supported by the node-red project.

Thanks,
Nick

**Comment by mapero** [comment]
Thanks for the hint. Updated the package.
